[project]
name = "book-api"
version = "0.1.0"
description = "FIAP - Tech challenge - 8MLET"
authors = [
    {name = "ricsandrini@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.32.5,<3.0.0)",
    "beautifulsoup4 (>=4.14.2,<5.0.0)",
    "sqlalchemy (>=2.0.44,<3.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "fastapi (>=0.121.3,<0.122.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "passlib[bcrypt] (>=1.7.4,<2.0.0)",
    "python-dotenv (>=1.0.0,<2.0.0)",
    "alembic (>=1.14.0,<2.0.0)"
]

[tool.poetry]
name = "book-api"
version = "0.1.0"
description = "FIAP - Tech challenge - 8MLET"
authors = ["ricsandrini@gmail.com"]
readme = "README.md"
packages = [{include = "app", from = "."}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "black (>=25.11.0,<26.0.0)",
    "flake8 (>=7.3.0,<8.0.0)"
]
