"""Add UPC column to books table

Revision ID: 2b5aa3b0dbcd
Revises: 
Create Date: 2025-12-02 15:49:17.633073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b5aa3b0dbcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('upc', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'books', ['upc'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'upc')
    # ### end Alembic commands ###
